# # =========================

name: Run Ansible Playbook to install Client

on:
  push:
    branches:
      - Ansible-vault
jobs:
  run_ansible_playbook:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python venv and Ansible
        run: |
          python3.12 -m venv ~/ansible_venv
          source ~/ansible_venv/bin/activate
          pip install --upgrade pip
          pip install ansible

      - name: Disable SSH host key checking
        run: echo "ANSIBLE_HOST_KEY_CHECKING=False" >> $GITHUB_ENV

      - name: Install Ansible Galaxy Dependencies
        run: |
          ansible-galaxy collection install ansible.posix
          ansible-galaxy collection install ibm.storage_protect --force

      - name: Create Ansible Vault password file
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault_pass.txt

      - name: Run Playbooks with Vault
        working-directory: ${{ github.workspace }}
        run: |
          EXIT_CODE=0
          for playbook in tests/integration/targets/ba_client_install/test_ba_client_install_linux.yml; do
            echo "▶️ Running $playbook"
            ansible-playbook -i inventory "$playbook" \
              --extra-vars "{\"ba_client_version\": \"8.1.26.0\"}" \
              --vault-password-file vault_pass.txt || {
                echo "❌ Playbook failed: $playbook"
                EXIT_CODE=1
              }
          done
          exit $EXIT_CODE

      - name: Cleanup Vault password
        run: rm -f vault_pass.txt


#           exit $EXIT_CODE

